#!/bin/ksh
## CWI_PW ##

KAT_DOM=/appksi/ksi/cwipw
PLIK_OSAB=$HOME/cfg/osab_all_kody
LISTA_OSAB=`awk '{print $3}' $PLIK_OSAB`

DATA_LOGU=`date "+%Y-%m-%d"`
LOG="Proc_U0008_test_${DATA_LOGU}.log"

POLECENIE79="/appksi/ksi/procU0079/bin/tuxsprdom.sh"
POLECENIE78="/appksi/ksi/procU0078/bin/tuxsprser.sh"
POLECENIE81="/appksi/ksi/procU0081/bin/tuxsprkol.sh -h"

FILTR79_1='egrep "DOMENA|OK|NOTOK"'
FILTR79_2='egrep -v "zam|KONTROLA|Domeny|Domena|Uruchom"'
FILTR78='egrep Wszystkie'

TUXUSER="tuxaut tuxks tuxazb tuxkor tuxwew tuxrkw tuxplat tuxsoi tuxdok tuxzas tuxzts tuxdkw tuxkwar"

###############################################################################
# MENU OSAB
###############################################################################

echo ""
echo "================= WYBÓR OSAB ================="
i=1
for s in $LISTA_OSAB
do
  echo " $i) $s"
  eval OSAB_$i=$s
  i=$((i+1))
done

print -n "Podaj numer OSAB: "
read OSAB_NR

SELECTED_OSAB=$(eval echo \$OSAB_$OSAB_NR)

if [ -z "$SELECTED_OSAB" ]; then
  echo "BŁĄD: Nieprawidłowy wybór OSAB"
  exit 1
fi

###############################################################################
# MENU TUXUSER
###############################################################################

echo ""
echo "=============== WYBÓR TUXUSER ================"
i=1
for u in $TUXUSER
do
  echo " $i) $u"
  eval TUX_$i=$u
  i=$((i+1))
done

print -n "Podaj numer TUXUSER: "
read TUX_NR

SELECTED_TUX=$(eval echo \$TUX_$TUX_NR)

if [ -z "$SELECTED_TUX" ]; then
  echo "BŁĄD: Nieprawidłowy wybór TUXUSER"
  exit 1
fi

###############################################################################
# WŁAŚCIWE WYKONANIE
###############################################################################

(
for SERWER in $SELECTED_OSAB
do
  echo "=================================================================================="
  echo "Lacze z $SERWER" | tee -a SPR_${DATA_LOGU}.log
  echo "=================================================================================="

  for USER1 in $SELECTED_TUX
  do
    echo "================================== ${USER1} ========================================"

    AUTORYZACJA="/usr/bin/privrun -u ${USER1} /bin/ksh -c"
    PROFIL="cd /appksi/ksi/${USER1} && export LOGNAME=${USER1} && . ./.profile && export PS1 &&"
    SRODOWISKO_ODD=". /appksi/ksi/${USER1}/odd/cfg/odd.sh"
    SRODOWISKO_TJO=". /appksi/ksi/${USER1}/tjo/cfg/tjo.sh"

    # ODD
    ssh $SERWER "$AUTORYZACJA \"$PROFIL $SRODOWISKO_ODD ; $POLECENIE79\"" \
      | $FILTR79_1 | $FILTR79_2 | egrep -v "zam|Uruchom" | awk '{print $1,$2,$3}'

    ssh $SERWER "$AUTORYZACJA \"$PROFIL $SRODOWISKO_ODD ; $POLECENIE78\"" \
      | $FILTR78

    ssh $SERWER "$AUTORYZACJA \"$PROFIL $SRODOWISKO_ODD ; $POLECENIE81\"" \
      | egrep "^..:|^CZAS|^Brak"

    echo "__________________________________________________________________________________"
    echo ""

    # TJO
    ssh $SERWER "$AUTORYZACJA \"$PROFIL $SRODOWISKO_TJO ; $POLECENIE79\"" \
      | $FILTR79_1 | $FILTR79_2 | awk '{print $1,$2,$3}'

    ssh $SERWER "$AUTORYZACJA \"$PROFIL $SRODOWISKO_TJO ; $POLECENIE78\"" \
      | $FILTR78

  done
done
) | tee -a SPR_${DATA_LOGU}.log
